### ISSUE TITLE
From CMake to Bazel

### ISSUE THREAD

**Issue by derived-coder** [HappyCerberus/meetingcpp22-bazel#1]
Thanks for this Talk and repo to experiment with it!

Some addition:
Would be nice to have some guide how to convert your CMake project to Bazel.
Having a background as CMake user for years, I cannot find basic information like:
1. How to build Release/Debug/.. builds?
2. How link static/dynamically against libs?
3. How to link private/public against dependencies?
4. How to transitive depend on libs (so that their compiler settings, definitions get applied automatically)?
5. How to create export header?
6. How to create so library version?
7. ...

Maybe an idea for a next talk.

**Comment by HappyCerberus** [comment]
Bazel has excellent documentation, and there is little value in repeating things already covered in the official documentation.

Also, I'm not a CMake expert. 😅
